tasks:
  - command: source /opt/esp/idf/export.sh

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - https://github.com/espressif/vscode-esp-idf-extension@1.4.0
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
