tasks:
  - command: source /opt/esp/idf/export.sh

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - espressif.esp-idf-extension
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
